### ISSUE TITLE
Post-upload fails

### ISSUE THREAD

**Issue by mrowles** [cloudflare/pages-action#104]
As of about 5 hours ago, I am receiving this odd issue after a successful deployment to Cloudflare:

> npm WARN exec The following package was not found and will be installed: wrangler@2.20.1
npm WARN deprecated rollup-plugin-inject@3.0.2: This package has been deprecated and is no longer maintained. Please use @rollup/plugin-inject.
npm WARN deprecated sourcemap-codec@1.4.8: Please use @jridgewell/sourcemap-codec instead
Uploading... (193/194)
Uploading... (194/194)
✨ Success! Uploaded 1 files (193 already uploaded) (1.78 sec)
>
>✨ Deployment complete! Take a peek over at https://xxx.pages.dev/
npm notice 
npm notice New minor version of npm available! 10.1.0 -> 10.2.0
npm notice Changelog: <https://github.com/npm/cli/releases/tag/v10.2.0>
npm notice Run `npm install -g npm@10.2.0` to update!
npm notice 
undefined:1
<!DOCTYPE html>
> ^
>
>SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at Response.json (/home/runner/work/_actions/cloudflare/pages-action/v1/index.js:13368:23)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async createPagesDeployment (/home/runner/work/_actions/cloudflare/pages-action/v1/index.js:22105:9)
    at async /home/runner/work/_actions/cloudflare/pages-action/v1/index.js:22175:29

**Comment by holm** [comment]
We are seeing this also. We assumed this was due to the incident, but indications are on the status page that it [has been fixed](https://www.cloudflarestatus.com/incidents/msghx93bcjjd).

**Comment by lovasoa** [comment]
Cloudflare's API seems to be timing out. Tried with `curl -v "https://api.cloudflare.com/client/v4/accounts/$ACCOUNT_ID/pages/projects/$PROJECT/deployments" -H 'Authorization: Bearer XXX`

**Comment by WalshyDev** [comment]
This is resolved now :)
