### ISSUE TITLE
Unable to publish site, API return 503 and 504 errors

### ISSUE THREAD

**Issue by razonyang** [cloudflare/pages-action#105]
The job fails frequently.

- Jobs list: https://github.com/hugomods/site/actions/workflows/cloudflare-page.yaml?query=is%3Afailure
- 503 fail job: https://github.com/hugomods/site/actions/runs/6453048076/job/17515963221
- 504 fail job: https://github.com/hugomods/site/actions/runs/6454073460/job/17518863187

**Comment by bkniffler** [comment]
https://www.cloudflarestatus.com/

<img width="832" alt="Bildschirmfoto 2023-10-09 um 14 09 15" src="https://github.com/cloudflare/pages-action/assets/4349324/9f7e8fb5-3685-49af-bb22-85e788f6d357">
