### ISSUE TITLE
Update README GITHUB_TOKEN to DEPLOY_TOKEN

### ISSUE THREAD

**Issue by socketopp** [cloudflare/pages-action#111]
```
gitHubToken: ${{ secrets.GITHUB_TOKEN }}
```
Result in
```
 Failed to add secret. Secret names must not start with GITHUB_.  
```

`GITHUB_TOKEN`  is not a valid name so I suggest the README.md is updated. Better name would be [`DEPLOY_TOKEN`](https://github.com/hexojs/site/pull/1979/commits/c197dd4ce2b524329e5ad68f562951ef88d2a3e8)

See more:
https://github.com/github/docs/pull/12095

**Comment by WalshyDev** [comment]
GITHUB_TOKEN is actually correct per the last comment in that linked issue - https://github.com/github/docs/pull/12095#issuecomment-974285693

and the associated docs: https://docs.github.com/en/actions/security-guides/automatic-token-authentication#about-the-github_token-secret

There's no manual work needed to add this token, it's automatically available to all GitHub workflows.
