### ISSUE TITLE
Project not found. The specified project name does not match any of your existing projects.

### ISSUE THREAD

**Issue by seabeya** [cloudflare/pages-action#115]
(related issues: https://github.com/cloudflare/pages-action/issues/51)

```sh
API returned: {
  "result": null,
  "success": false,
  "errors": [
    {
      "code": 8000007,
      "message": "Project not found. The specified project name does not match any of your existing projects."
    }
  ],
  "messages": []
}
```

This error occurs when attempting to publish to a non-existing Cloudflare Pages project using GitHub Actions.

There are two options/ways to create a project as I see:

### Option/Way 1: `Create by importing an existing Git repository`.

- Process: `Connect the GitHub repo` -> `Name the new project` -> `Click deploy to finish the setup`.

Then, pause automatic deployments (from Build & deployment settings) because I'm going to use GitHub Actions for that. I don't need Cloudflare to do this for me.

Now, every time I push, there will be two deployments: one created by Cloudflare (skipped), and one created by my GitHub workflow. 

![image](https://github.com/cloudflare/pages-action/assets/35802638/c3a25015-e270-411c-bf46-48fc630dfb00)

### Option/Way 2: `Create using direct upload`.

- Process: `Name the new project` -> `Click "Create project"` (No need to finish the process by clicking deploy. All we need was creating a project).

![image](https://github.com/cloudflare/pages-action/assets/35802638/475dff13-2ed0-432a-9503-1cbc52f1a6fa)

---

The question is:

Is "Create using direct upload" the way to go to create a project when you do custom deployments using GitHub Actions?

**Comment by WalshyDev** [comment]
> Is "Create using direct upload" the way to go to create a project when you do custom deployments using GitHub Actions?

Yes it is, the GitHub Action does a Direct Upload - https://developers.cloudflare.com/pages/how-to/use-direct-upload-with-continuous-integration
