### ISSUE TITLE
Using CF_PAGES_URL

### ISSUE THREAD

**Issue by daviddavo** [cloudflare/pages-action#128]
To deploy something like Hugo pages, I need to set the baseURL, can I access the CF_PAGES_URL env variable?

**Comment by AgustinRamiroDiaz** [comment]
I think it's only available as the [`url` output](https://github.com/cloudflare/pages-action/tree/v1?tab=readme-ov-file#outputs)

I think this means that you'd need to deploy twice in order to get the `url` on the first deploy, and then update it in the second one

**Comment by nprogers** [comment]
The second deployment will also have its own unique URL, different from the first. CF_PAGES_URL environment variable is only available during build time within the Pages CI system. I suggest using a branch alias to find the deterministic URL

https://github.com/marketplace/actions/cloudflare-pages-branch-alias
