### ISSUE TITLE
More magic ✨

### ISSUE THREAD

**Issue by GregBrimble** [cloudflare/pages-action#2]
- PR comments
- Commit messages
- Alias URLs
- Anything else?

**Comment by DaniFoldi** [comment]
GitHub added Job Summaries to Actions [announcement here from 09 May](https://github.blog/2022-05-09-supercharging-github-actions-with-job-summaries/), which could be a nice addition, bringing it closer to how the App commented after deployment

**Comment by IanVS** [comment]
It seems like most of this is being tracked in other issues.
