### ISSUE TITLE
Uploading _headers from Create React App

### ISSUE THREAD

**Issue by sirganya** [cloudflare/pages-action#20]
If I place a _header file in the public folder of my CRA and build locally the _headers file appears in the build folder.

When I run the same build using GitHub actions and upload to Pages the _headers file is not uploaded.

Does pages-action ignore it?

**Comment by sirganya** [comment]
<img width="917" alt="Screenshot 2022-07-13 at 07 43 53" src="https://user-images.githubusercontent.com/551096/178668439-aa227519-ef02-48fc-b28e-65da21495c33.png">

**Comment by Menci** [comment]
Did you test whether the headers actually take effect or not? Even for git-based automatically build & deploy, Pages sites' `_headers` are not really appearing in the site.
