### ISSUE TITLE
Handle `pull_request` events better

### ISSUE THREAD

**Issue by RichiCoder1** [cloudflare/pages-action#22]
Right now, Cloudflare's default behaviors for `pull_request` events are kinda wonky. Because PR events are against a _merged_ commit and this action assumes `push` events, it's reporting `HEAD` for the current branch and it also isn't reporting the correct commit to the GitHub Deployments API which results in deployments not showing up on their appropriate PR.

Willing to contribute fixes for both of these.

**Comment by olup** [comment]
I'll be super interested for a fix on this. Is there a fork already ?
