### ISSUE TITLE
Option to disable creating a github deployment

### ISSUE THREAD

**Issue by jylin** [cloudflare/pages-action#27]
I don't use the github deployment feature, so would it be possible to add a setting to be able to disable it? This would also remove the need for the "deployments: write" permission.

It would also remove the need to have the action require GitHub deployments write permissions and needing to pass in a GitHub token.

**Comment by nlnw** [comment]
It would also remove the need to have the action require GitHub deployments write permissions and needing to pass in a GitHub token.

**Comment by IanVS** [comment]
This is possible now in 1.3.0 by not passing a github token.
