### ISSUE TITLE
Error: Unable to resolve action `cloudflare/pages-action@1`, unable to find version `1`

### ISSUE THREAD

**Issue by ptim** [cloudflare/pages-action#3]
Hi! Testing this out for the first time, hitting some bumps:

```
Current runner version: '2.291.1'
Operating System
Virtual Environment
Virtual Environment Provisioner
GITHUB_TOKEN Permissions
Secret source: Actions
Prepare workflow directory
Prepare all required actions
Getting action download info
Error: Unable to resolve action `cloudflare/pages-action@1`, unable to find version `1`
```

I attempted removing the version number, but got:

> the `uses' attribute must be a path, a Docker image, or owner/repo@ref

Then setting version 1.0.0, but:

> Unable to resolve action `cloudflare/pages-action@1.0.0`, unable to find version `1.0.0`

**Comment by ptim** [comment]
Ahh! The correct syntax for `owner/repo@ref` seems to be: 

```yaml
# ...
  - name: Publish
     uses: cloudflare/pages-action@v1.0.0
     # ...
```

https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstepsuses

**Comment by ptim** [comment]
The docs over at https://developers.cloudflare.com/pages/how-to/use-direct-upload-with-continuous-integration/#use-github-actions are also incorrect on this point 👍

**Comment by DaniFoldi** [comment]
To maintain the intention of locking only the major version, the ref should be `@v1` which is resolved to the latest version under the specifier major.

Check https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-using-versioned-actions

**Comment by ptim** [comment]
I did try this initially, but it errors with:

> Unable to resolve action `cloudflare/pages-action@v1`, unable to find version `v1`

**Comment by DaniFoldi** [comment]
You are correct in that it would still require the team to tag the release commit with `v1` as well as `v1.x.x` - which is the convention for most actions.

**Comment by ptim** [comment]
Aha! Thanks for clarifying!

Long story short, as it stands, only one config currently works, and it's different from both sets of docs: 

- ✅ `@v1.0.0`
- ❌ `@v1` (requires additional release tagging) [per cloudflare docs](https://developers.cloudflare.com/pages/how-to/use-direct-upload-with-continuous-integration/#set-up-a-workflow)
- ❌ `@v1.x.x`
- ❌ `@1` [per README.md](https://github.com/cloudflare/pages-action/blob/main/README.md?plain=1#L28)
- ❌ `@1.0.0`

@GregBrimble, reckon you could tag each release for its major version, too? 

> Error: Unable to resolve action `cloudflare/pages-action@v1.x.x`, unable to find version `v1.x.x`

**Comment by GregBrimble** [comment]
Hey folks, sorry about that. We've just switched over to `1.0.0` and `1` rather than `v1.0.0` to make things a bit easier for everyone. And [I've just put up a PR to update the docs](https://github.com/cloudflare/cloudflare-docs/pull/4502). If you're still having difficulty referencing the Action with `uses: cloudflare/pages-action@1`, please give let us know.

**Comment by ptim** [comment]
Works for me, thanks 🙏
