### ISSUE TITLE
Documentation update for YOUR_ASSET_DIRECTORY, YOUR_PROJECT_NAME, and YOUR_ACCOUNT_ID

### ISSUE THREAD

**Issue by tomdot-dev** [cloudflare/pages-action#34]
Two items should be documented:
- YOUR_ASSET_DIRECTORY: it should indicate that if it's the current directory, it's `.`. I originally used `/` as what I wanted to use the root of my repo. However, doing so, the deployment failed with permission errors.
- YOUR_PROJECT_NAME: it should indicate it is the name of the project in pages.

Another item should have its documentation updated: "Get account ID". The first paragraph is confusing.

Let me know if you'd like me to open a PR for all that (or one for each item).

**Comment by sercanov** [comment]
also an explanation for `gitHubToken` would be great

**Comment by nprogers** [comment]
Thanks for the suggestions on updated docs. It looks like those changes are reflected in the README. I'm closing this ticket as done.
