### ISSUE TITLE
cloudflare/pages-action@1 still points to v1.1.0

### ISSUE THREAD

**Issue by andersk** [cloudflare/pages-action#38]
The [`1` tag](https://github.com/cloudflare/pages-action/commits/1) still points to the same commit as `1.1.0` and `v1.1.0`, so users writing `uses: cloudflare/pages-action@1` as documented are still getting the version with the `set-output` deprecation warning. The tag needs to be repointed to `v1.2.0`.

**Comment by gonzaleztroyano** [comment]
Same issue here.

The [line 28 of README](https://github.com/cloudflare/pages-action/blob/main/README.md?plain=1#L28) should point to the last tag available for this action. 

From:
```yml
           uses: cloudflare/pages-action@1
```
To (at the time of commenting this issue):
```yml
           uses: cloudflare/pages-action@1.2.0
```

Thanks!

**Comment by andersk** [comment]
@gonzaleztroyano No, it is correct for the README to refer to the major release tag `1`. This tag should just be repointed in Git to the latest `v1.x.x`  release whenever a release is made. That lets users run the latest compatible release without manually updating their workflow files every time. See [About custom actions § Using tags for release management](https://docs.github.com/en/actions/creating-actions/about-custom-actions#using-tags-for-release-management).

**Comment by gonzaleztroyano** [comment]
Awesome! Thanks for the info, @andersk! Now I understand that the README is correct but it is the "internal pointer" which should be pointed to the newer version. 🙃🙃

**Comment by andersk** [comment]
The [`1` tag](https://github.com/cloudflare/pages-action/commits/1) _still_ points to the same commit as `1.1.0` and `v1.1.0`. Please reopen.

**Comment by WalshyDev** [comment]
There hasn't been a release yet.

**Comment by andersk** [comment]
There was `v1.2.0`. The `1` tag still points to `v1.1.0`.

(I understand that if there’s a future `v1.3.0`, this action will theoretically create `v1` pointing to `v1.3.0`. But even that’s not going to fix this, because `1` ≠ `v1`, `1` is what’s documented in `README.md`, and `1` will still point to `v1.1.0`. In any case, why wait for `v1.3.0` when you can fix this now by simply fixing a tag?)

**Comment by WalshyDev** [comment]
Release has been done. 1.3.0 now points to `v1` and `1`. As stated in the release, the `1` tag is considered deprecated now. Please change to `v1`
