### ISSUE TITLE
[Request] Nicer CF deployment descriptions

### ISSUE THREAD

**Issue by IanVS** [cloudflare/pages-action#48]
Currently, the description of the builds in Cloudflare are of the form:

`Merge 4a618058856d794a1240bfc87c4ddf8294a15f36 into 436b31bdb8e6c124dc51133e6ba2d268e62aecda`

It would be great if the PR's last commit summary could be used instead.

**Comment by limakzi** [comment]
@IanVS I agree. 
I would allow the end user to provide environment description.
At the very same time, I am getting awful environment descriptions for deployments, as attached in screenshot below.  _Awful_, is of course, personal opinion. I would prefer have a parameter to set: `pr-#id [preview]`.

![image](https://user-images.githubusercontent.com/50334623/224022113-37d0dd91-6367-4c93-a322-6b88bd804378.png)

**Comment by nprogers** [comment]
@IanVS @limakzi Is this an issue with [wrangler-action](https://github.com/cloudflare/wrangler-action)? 
We're porting pages-action there and stepping up the maintenance. I'm pretty new to GitHub actions/deployments/environments, so I'd be better able to assist if you could provide a more specific request, meaning a specific input or output for the action and what it should do.

**Comment by nprogers** [comment]
Ok I see. Have you tried passing through the commit message with  `-- commit message` option in the [wrangler command](https://developers.cloudflare.com/workers/wrangler/commands/#deploy-1)?

**Comment by IanVS** [comment]
I haven't.  Is it not possible for wrangler itself to choose a more useful default message?

**Comment by nprogers** [comment]
It looks like wrangler does [attempt to create a useful message](https://github.com/cloudflare/workers-sdk/blob/271832a45ad92cc41b859a7c2698857ae78a9e9c/packages/wrangler/src/pages/deploy.tsx#L326) based on your last commit. You should file a feature request with that team if you feel it should do something different. This isn't something we can do inside an action.

**Comment by limakzi** [comment]
I see _closing as not planned_ is enojable. 🥸
