### ISSUE TITLE
bug: Unexpected input 'workingDirectory'

### ISSUE THREAD

**Issue by TravisFrankMTG** [cloudflare/pages-action#57]
Just set this up in my monorepo and immediately ran into this:

![image](https://user-images.githubusercontent.com/65560782/215131265-e698bc49-c329-43da-8ed0-5674caee003b.png)

I see `workingDirectory` in `action.yml`, so I'm not sure what's up here.

**Comment by GregBrimble** [comment]
Ah, apologies. This will be available as soon as we cut the next release.

**Comment by leads** [comment]
Just repeating the above as it's happening to me just now, using `uses: cloudflare/pages-action@v1`

**Comment by jonatansberg** [comment]
@leads Seems like they still haven't cut a new release. `cloudflare/pages-action@main` works in the mean time.

**Comment by giladv** [comment]
would really love to see this new release soon, thanks!
