### ISSUE TITLE
CircleCI Orb ?

### ISSUE THREAD

**Issue by mattkoch-bb** [cloudflare/pages-action#64]
Is there an equivalent mechanism to getting outputs from a wrangler command, similar to this Github Action, for Circle CI? For example, We used the `url` output of this action to get the pages deployment URL, so we could run Cypress tests against it. I haven't been able to find an equivalent CircleCI Orb, for example.

https://github.com/cloudflare/pages-action#outputs

**Comment by nprogers** [comment]
This definitely makes it hard to use wrangler to chain automation. I'm closing this issue here, as it would not be handled within the pages-action repo. I found a [wrangler issue](https://github.com/cloudflare/workers-sdk/issues/2437) if you'd like to track/+1 there.
