### ISSUE TITLE
Unable to resolve action `cloudflare/pages-action@1`

### ISSUE THREAD

**Issue by haithamalnaeb** [cloudflare/pages-action#66]
I'm using the documentation code,
but a few hours ago I start getting this error on all repo in "Set up job" step

Error: Unable to resolve action `cloudflare/pages-action@1`, the provided ref `1` is the shortened version of a commit SHA, which is not supported. Please use the full commit SHA `1631a1483b9131d13c61c8c9e6db68f7c7f5d0ee` instead.

Maybe the doc should be updated to cloudflare/pages-action@v1.4.0 by default

**Comment by haithamalnaeb** [comment]
Workaround:

I just noticed that the documents reference to `v1` now instead `1`, which kind of work, but has bug so it didn't work
also `v1.4.0` has the same bug

So I'm using an old commit that works until the bug is fixed,

this one works for me:
`cloudflare/pages-action@22d9e5e143c6f9400b438a489e8d434b416d235d`

**Comment by krisgardiner** [comment]
Updating to `cloudflare/pages-action@v1` worked for me.

**Comment by WalshyDev** [comment]
GitHub isn't liking the deprecated `1` tag because the commit starts with a `1`... that's great.

Yeah as @krisgardiner said, `v1` is the tag that should now be used. The old `1` tag was deprecated a few releases back. Please switch to `v1`.

**Comment by WalshyDev** [comment]
Done a new release to fix an unrelated issue but this should also resolve this one for now.

**Note though** the `1` tag is deprecated. Please switch to `v1` to continue getting updates. We will stop publishing to `1` soon.
