### ISSUE TITLE
Make GitHub deployments opt-out, not opt-in

### ISSUE THREAD

**Issue by aaronadamsCA** [cloudflare/pages-action#69]
To enable GitHub [deployments](https://docs.github.com/en/rest/deployments/deployments) and [deployment statuses](https://docs.github.com/en/rest/deployments/statuses) today, you need to pass in your GitHub token manually:

```
          # Optional: Enable this if you want to have GitHub Deployments triggered
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
```

IMO this is a bad API for a few reasons:

- The name `gitHubToken` doesn't match the behaviour "enable GitHub deployments".
- The value is unnecessary; a GitHub Action can always access `github.token`.
- Disabling deployments is an edge case; I expect most users would prefer to have deployment statuses.

I'd like to suggest the following changes:

- Set the default value of `gitHubToken` to `${{ github.token }}`. The user would only need to set `gitHubToken` if for some reason they wanted to use a different token.
- Add new input `createDeploymentStatus`, optional, default value `true`.

With these changes, a subset of users could still disable deployment statuses or override the GitHub token, but everyone else would benefit from simpler setup with more default features.

I'm happy to contribute this change if it's desired. I expect it would require a major version bump.

**Comment by nprogers** [comment]
@aaronadamsCA Thanks for your suggestion! We're working on deprecating this repo, and moving everything to [wrangler-action](https://github.com/cloudflare/wrangler-action). We're tracking deployments support [here](https://github.com/cloudflare/wrangler-action/issues/274), although I'm not sure yet that we'll be switching to opt-out vs opt-in.

**Comment by aaronadamsCA** [comment]
That's great @nprogers, I'll close this and add a note over there that (whether opt-in or opt-out) the deployment feature should be controlled using a boolean, since actions can always access `github.token`.
