### ISSUE TITLE
Allow GH Actions to access a site via Access policies?

### ISSUE THREAD

**Issue by mattkoch-bb** [cloudflare/pages-action#77]
We have a job that deploys to CloudFlare via direct upload, and we're looking to have it also run some end to end tests using the deployed URL after that's finished. We don't want these URLs universally open to the world as they are production like environments that we want to limit access to. Can we set up an Access Policy in Cloudflare that would allow GitHub Actions to access URLs?

https://developers.cloudflare.com/cloudflare-one/policies/access/

**Comment by mattkoch-bb** [comment]
@WalshyDev How do I configure the action to send the appropriate headers as indicated in the https://developers.cloudflare.com/cloudflare-one/identity/service-tokens/#connect-your-service-to-access section?

**Comment by WalshyDev** [comment]
That's a question for whatever you're using for your end to end tests. 

They're just HTTP headers, so however you add them into whatever tool.

With curl it's just:
```
curl -H 'CF-Access-Client-Id: <Client ID>' -H 'CF-Access-Client-Secret: <Client Secret>' https://example.pages.dev/
```

**Comment by mattkoch-bb** [comment]
Oh right, my mistake. Long day :)
