### ISSUE TITLE
Nothing is here yet

### ISSUE THREAD

**Issue by IanVS** [cloudflare/pages-action#81]
I'm using this action, and then shortly afterwards I snapshot the site with Percy.io.  I've noticed that sometimes, the snapshots fail because it seems the deployment is not fully finished, and the pages all look like this:

<img width="1131" alt="image" src="https://user-images.githubusercontent.com/4616705/234720242-f793de5d-2589-4a73-9ca9-43decde33765.png">

Is there a way to cause the action to wait until the deploy is fully finished?  Or do I need to use https://github.com/WalshyDev/cf-pages-await in addition to this action?

**Comment by WalshyDev** [comment]
You can poll it yourself in an action with something like:
```yaml
- name: Poll
  run: |
    until $(curl --output /dev/null -s -I -f ${{  steps.publish.outputs.url }}); do
      printf '.'
      sleep 2
    done
```
(untested)

My `cf-pages-wait` will wait for a build not for a deployment to be ready.

**Comment by JohnMaguire** [comment]
@WalshyDev Does this seem like a common enough use case to warrant first class support in the Action? It'd be nice to not have to duplicate the shell in each repo.
