### ISSUE TITLE
"Unable to find pages project" error even though deploy is successful

### ISSUE THREAD

**Issue by NielsKersic** [cloudflare/pages-action#84]
Every time the Action runs, it fails with the following error

<img width="668" alt="Screenshot 2023-05-14 at 23 12 23" src="https://github.com/cloudflare/pages-action/assets/10178648/49c54916-031a-4365-84f8-279b259a8694">

The project name is correct however. In fact, when I go to the Deployments tab in the Pages dashboard, I can see that the deploy was successful.

I am more than a little bit confused.

**Comment by WalshyDev** [comment]
Added some better error messaging which should help you track what is going wrong :)

**Comment by NielsKersic** [comment]
Very helpful, thank you!
