### ISSUE TITLE
CF github app deployment status not updated

### ISSUE THREAD

**Issue by Mahmoudgalalz** [cloudflare/pages-action#90]
I don't know where I can report this issue

What happend ?

I used auto deploy of pages via CF github app that's trigger the push event

the problem is, I deleted a deployment, so the github app is in a pending status for more than 2h

and I wanna trigger another deploy, and I cannot stop it

**Comment by WalshyDev** [comment]
Closing as this is not related to pages-action.

The GitHub event being pending should not prevent you from doing more deployments, we do not check or care about that event status. If you are having issues still, please join the [Discord](https://discord.cloudflare.com) and seek support there.
